services:
  - type: web
    name: magcha-flask-app
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENV
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
    autoDeploy: true
